[config]
schemaVersion = "0.0.1"

[package]
namespace = "jcruse03"
name = "Cross_Server_Portals_Continued"
versionNumber = "1.3.2"
description = "Valheim 1.0 continuation of lunar91's Cross Server Portals. Link servers and local worlds through portals."
websiteUrl = "https://github.com/jcruse03/CrossServerPortals-Continued"
containsNsfwContent = false

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2350"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./artifacts/tcli"

[[build.copy]]
source = "./artifacts/bin/Release/ValheimCrossServerPortals.dll"
target = "ValheimCrossServerPortals.dll"

[[build.copy]]
source = "./CHANGELOG.md"
target = "CHANGELOG.md"

[publish]
repository = "https://thunderstore.io"
communities = ["valheim"]

[publish.categories]
valheim = ["mods", "transportation", "utility", "client-side", "server-side"]
